In [41]:
import pandas as pd
import numpy as np
import sklearn
import sklearn.metrics as met

In [47]:
x=[[1,2,3],[3,4,6]]
y=[3,5]
met.pairwise.euclidean_distances(x)[0,1]

4.123105625617661

In [7]:
lookup = pd.read_csv('./Desktop/lookupid.csv')
resultscluster = pd.read_csv('./Desktop/resultsCluster2.csv')

In [18]:
resultscluster

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,label,index
0,0,-0.206506,-0.563439,0.317522,-5.456616,-0.731626,13.884357,2.997422,-5.266460,-0.487689,...,-0.529717,6.533639,0.111057,4.093718,0.013268,-0.634849,-3.532786,0.673224,0,32281
1,1,11.378760,11.205390,-0.078918,-0.829518,8.742121,3.368638,3.177336,0.994633,4.529009,...,0.858570,-5.393561,-0.204981,2.342823,-2.083355,3.216719,1.471081,3.454048,6,5114
2,2,12.371966,3.590411,-3.522050,5.666310,-4.425759,-1.756962,-1.592753,-2.897913,1.362337,...,-0.746888,-1.335666,-2.428528,-6.055771,8.931566,2.804498,-1.203195,-5.519162,1,28977
3,3,3.612641,1.916101,-5.679057,-3.580982,-2.101428,-3.498208,-3.441342,2.198112,-1.975402,...,1.802897,1.334781,-1.431290,0.249102,0.320964,-0.148144,1.782006,-3.635773,6,9253
4,4,12.221680,3.548776,-3.486992,5.591969,-4.393261,-1.758415,-1.572722,-2.870134,1.353203,...,-0.742952,-1.328995,-2.405819,-5.995705,8.844525,2.774389,-1.186308,-5.457356,1,9969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,12289,-5.563787,-0.551937,-1.758460,0.742158,0.978225,-1.486863,-0.486866,-0.427194,0.590843,...,0.324216,-0.678987,-1.172959,0.087547,-0.742918,-0.399164,-0.562919,-0.264116,2,9316
12290,12290,-5.641779,-0.547652,-1.816086,0.827249,1.042877,-1.473724,-0.516712,-0.439232,0.596085,...,0.345096,-0.679892,-1.206742,0.086603,-0.765741,-0.402581,-0.597230,-0.298489,2,5543
12291,12291,-6.001744,-0.527872,-2.082053,1.219979,1.341268,-1.413085,-0.654463,-0.494793,0.620278,...,0.441465,-0.684071,-1.362662,0.082246,-0.871083,-0.418352,-0.755587,-0.457130,2,5621
12292,12292,-6.061738,-0.524576,-2.126380,1.285433,1.390999,-1.402979,-0.677422,-0.504053,0.624310,...,0.457527,-0.684767,-1.388648,0.081519,-0.888640,-0.420980,-0.781980,-0.483570,2,6133
12293,12293,-4.453553,0.231509,1.890647,-2.456609,-1.301672,-0.651881,-1.100887,-2.816706,-0.310932,...,0.683846,-0.805886,-2.699940,0.296173,-1.652221,-0.697663,-1.342987,-0.948982,0,26081

In [138]:
lookup[lookup['name']=='naruto']['anime_id'].item()
resultscluster[resultscluster['index']==20]['label'].item()
c = resultscluster[resultscluster['label']==4].iloc[:,1:-2][resultscluster['index']==263].values.tolist()[0]
#resultscluster.iloc[[0,1]]
#resultscluster
#esultscluster.loc[0]

/tmp/ipykernel_757/108052833.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  c = resultscluster[resultscluster['label']==4].iloc[:,1:-2][resultscluster['index']==263].values.tolist()[0]

In [160]:
def dist(x, center):
    X = x.iloc[:-2].values.tolist()
    distmatrix = [X,center]
    #print(len(X))
    #print(len(center))
    #print(distmatrix)
    distmatrix =np.array(distmatrix)
    distance = met.pairwise.euclidean_distances([X,center])
    return distance[0,1]

In [161]:
p = [1,6,8,9,22,7,10,5]
res = sorted(range(len(p)), key = lambda sub: p[sub])[:3]
res

[0, 7, 1]

In [178]:
def find_anime(name):
    lookup['name'] = lookup['name'].str.lower()
    # add a exception handler
    
    id = lookup[lookup['name']==name]['anime_id'].item()
    cluster_no = resultscluster[resultscluster['index']==id]['label'].item()
    data = resultscluster[resultscluster['label']==cluster_no].iloc[:,1:]
    center = data[resultscluster['index'] == id].iloc[:,:-2].values.tolist()[0]
    data = data[data['index'] != id]
    dista = []
    for i in range(0, len(data)):
        d = dist(data.iloc[i],center)
        dista.append(d)
    
    res = sorted(range(len(dista)), key = lambda sub: dista[sub])[:2]
    #print(res)
    output = data.iloc[res]
    #print(output) 
    output_index = output['index'].values.tolist()
    for i in range(0,len(output_index)):
        anime = lookup[lookup['anime_id'] == output_index[i]]['name']
        print(anime)

In [185]:
ani ='toushindai my lover: minami tai mecha-minami'
find_anime(ani.lower())

/tmp/ipykernel_757/12369200.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  center = data[resultscluster['index'] == id].iloc[:,:-2].values.tolist()[0]

12267    lovely series
Name: name, dtype: object
12269    milky gal: cats ai
Name: name, dtype: object